os: linux
language: python
python:
  - "3.6"

env:
# Test a recipe before you even open a MELPA pull request:
  - RECIPE='(shx :repo "riscy/shx-for-emacs" :fetcher github)'
  - RECIPE='(bifocal :repo "riscy/bifocal-mode" :fetcher github)'
# If you already have a pull request open, specify as below:
  - MELPA_PR_URL=https://github.com/melpa/melpa/pull/4749
# Some (older) MELPA PR's have errors, but we use them to test:
  - >-
    MELPA_PR_URL=https://github.com/melpa/melpa/pull/5004
    EXPECT_ERROR=2
  - >-
    MELPA_PR_URL=https://github.com/melpa/melpa/pull/5050
    EXPECT_ERROR=2

install:
  - pip install requests
  - pytest --doctest-modules

script:
  - python melpazoid.py
