os: linux
language: python
python:
  - "3.6"

env:
# Test a recipe before you even open a MELPA pull request:
  - RECIPE='(shx :repo "riscy/shx-for-emacs" :fetcher github)'
# If you already have a pull request open, specify as below:
  - MELPA_PR_URL=https://github.com/melpa/melpa/pull/4749
# Use these existing to test (but allow for errors):
  - >-
    MELPA_PR_URL=https://github.com/melpa/melpa/pull/3041
    EXPECT_ERROR=2
  - >-
    RECIPE='(magit :fetcher github :repo "magit/magit" :files ("lisp/magit" "lisp/magit*.el" "lisp/git-rebase.el" "Documentation/magit.texi" "Documentation/AUTHORS.md" "LICENSE" (:exclude "lisp/magit-libgit.el")))'
    EXPECT_ERROR=2
  - >-
    MELPA_PR_URL=https://github.com/melpa/melpa/pull/5004
    EXPECT_ERROR=2
  - >-
    MELPA_PR_URL=https://github.com/melpa/melpa/pull/5050
    EXPECT_ERROR=2

install:
  - pip install .
  - pip install mypy
  - pytest --doctest-modules
  - mypy --ignore-missing-imports .

script:
  - python melpazoid/melpazoid.py
