os: linux
language: python
python:
  - "3.6"

# TODO: make it unnecessary to specify both CLONE_URL and RECIPE
env:
# Test a recipe before you even open a MELPA pull request:
  - >-
    CLONE_URL='https://github.com/riscy/shx-for-emacs'
    RECIPE='(shx :repo "riscy/shx-for-emacs" :fetcher github)'
  - >-
    CLONE_URL='https://github.com/riscy/bifocal-mode'
    RECIPE='(bifocal :repo "riscy/bifocal-mode" :fetcher github)'
# If you already have a pull request open, specify as below:
  - MELPA_PR_URL=https://github.com/melpa/melpa/pull/4749
  - >-
    MELPA_PR_URL=https://github.com/melpa/melpa/pull/5004
    NO_ERROR=1
  - >-
    MELPA_PR_URL=https://github.com/melpa/melpa/pull/5050
    NO_ERROR=1

install:
  - pip install requests
  - pytest --doctest-modules

script:
  - python melpazoid.py
